pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
        }
        steps {
            sh 'python -s py_compile src/sum.py src/main.py'
            stash(name: 'compiled-results', includes: 'src/*.py*')
        }

    }
}