# sample web and DB service
version: "3"

services:
  db:  # DB Service
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on: 
      - db