apiVersion: apps/v1
kind: Deployment
metadata:
  name: pywebsvc
spec:
  selector:
    matchLabels:
      app: pywebsvc
  replicas: 1
  template:
    metadata:
      labels:
        app: pywebsvc
    spec:
      containers:
      - name: pyweb
        image: mvijay/pyweb:latest
        imagePullPolicy: Never
